# Generated by Django 5.0.6 on 2026-05-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('hex_code', models.CharField(help_text='e.g. #FFFFFF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Front Chest, Back, Left Sleeve', max_length=50)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('print_size', models.CharField(choices=[('small', 'Small (chest logo ~10cm)'), ('medium', 'Medium (full chest ~25cm)'), ('large', 'Large (full back ~30cm)')], default='medium', max_length=10)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Added to product base price, in INR', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. S, M, L, XL, XXL', max_length=10, unique=True)),
                ('label', models.CharField(help_text='e.g. Small, Medium', max_length=30)),
                ('chest_inches', models.IntegerField(blank=True, null=True)),
                ('length_inches', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('garment_type', models.CharField(choices=[('tshirt', 'T-Shirt'), ('polo', 'Polo'), ('hoodie', 'Hoodie'), ('tank', 'Tank')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in INR (no print)', max_digits=8)),
                ('glb_url', models.CharField(blank=True, help_text='Path served from /public, e.g. /models/tshirt.glb', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_colors', models.ManyToManyField(blank=True, related_name='products', to='catalog.color')),
                ('available_print_types', models.ManyToManyField(blank=True, related_name='products', to='catalog.printtype')),
                ('available_sizes', models.ManyToManyField(blank=True, related_name='products', to='catalog.size')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, help_text='Extra over product base price (e.g. XXL surcharge)', max_digits=8)),
                ('stock_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size')),
            ],
            options={
                'ordering': ['product', 'color', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
