# Generated by Django 5.2.15 on 2026-06-11 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=120)),
                ('destination_city', models.CharField(max_length=120)),
                ('pickup_date', models.DateField()),
                ('capacity_tons', models.DecimalField(decimal_places=1, max_digits=5)),
                ('used_tons', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trucks.trucktype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('goods_type', models.CharField(max_length=120)),
                ('weight_tons', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pickup_date', models.DateField()),
                ('mode', models.CharField(choices=[('full', 'Full truck load'), ('shared', 'Part load (shared)')], default='full', max_length=10)),
                ('share_pct', models.FloatField(default=1.0, help_text='Fraction of truck this load occupies')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=10)),
                ('fare_base', models.PositiveIntegerField(default=0)),
                ('fare_distance', models.PositiveIntegerField(default=0)),
                ('fare_surcharge', models.PositiveIntegerField(default=0)),
                ('fare_surcharge_label', models.CharField(blank=True, max_length=80)),
                ('fare_gst', models.PositiveIntegerField(default=0)),
                ('fare_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_bookings', to='locations.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bookings', to='locations.location')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucks.truck')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trucks.trucktype')),
                ('share_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.sharedbookinggroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='bookings.booking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
