# Generated by Django 5.2.15 on 2026-06-11 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('capacity_tons', models.DecimalField(decimal_places=1, max_digits=5)),
                ('capacity_label', models.CharField(help_text="e.g. 'up to 1 ton'", max_length=60)),
                ('example_use', models.CharField(blank=True, max_length=160)),
                ('base_fare', models.PositiveIntegerField(help_text='Flat ₹ base fare')),
                ('per_km_rate', models.PositiveIntegerField(help_text='₹ per km')),
                ('image', models.ImageField(blank=True, null=True, upload_to='truck_types/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL if no file uploaded')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'capacity_tons'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On trip'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rc_document', models.FileField(blank=True, null=True, upload_to='truck_docs/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='truck_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL)),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='trucks.trucktype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
